package it.cnr.ilc.maia.model;

public enum TileType {
    TEXT,
    ONTOLOGY,
    LEXICON,
    CORPUS,
    LAYERS_LIST,
    SEARCH,
    LEXICON_EDIT,
    DICTIONARY,
    DICTIONARY_EDIT,
    ONTOLOGY_EXPLORER,
    ONTOLOGY_CLASS_VIEWER,
    ONTOLOGY_OBJECT_PROPERTY_VIEWER,
    ONTOLOGY_DATA_PROPERTY_VIEWER,
    ONTOLOGY_INDIVIDUAL_VIEWER,
}
